apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      serviceAccountName: internal-app
      containers:
      - name: app-python
        image: nikitagrigorenko/app_python
        ports:
        - containerPort: 5000